apiVersion: v2
appVersion: "1.16.0"
description: A Helm chart for Volumez-CSI container
name: volumez-csi
type: application
version: 1.10.0
icon: https://volumez.com/wp-content/uploads/2022/01/Group-2273.svg
dependencies:
  - name: cert-manager
    version: v1.11.0
    repository: https://charts.jetstack.io
    alias: certmanager
    condition: cert-manager.enabled
